// Generated by CoffeeScript 1.6.3
var setting;

setting = require('../setting');

module.exports = function(app) {
  return app.get('/', function(req, res) {
    return res.render('index', {
      title: setting.title,
      brand: setting.brand
    });
  });
};
