// Generated by CoffeeScript 1.6.3
var request, setting;

setting = require('../setting');

request = require('request');

module.exports = function(app) {
  app.get('/', function(req, res) {
    return res.render('index', {
      title: setting.title,
      brand: setting.brand
    });
  });
  app.get('/login', function(req, res) {
    return res.render('login', {
      title: setting.title,
      brand: setting.brand
    });
  });
  return app.get('/reg', function(req, res) {
    return res.render('reg', {
      title: setting.title,
      brand: setting.brand
    });
  });
};
