// Generated by CoffeeScript 1.6.3
var Dbauth, setting;

setting = require('../setting');

Dbauth = require('../lib/dbauth');

module.exports = function(app) {
  app.get('/users/auth/douban', function(req, res) {
    return res.redirect('https://www.douban.com/service/auth2/auth?response_type=code&client_id=' + setting.douban_auth.client_id + '&redirect_uri=' + setting.douban_auth.dev_host + 'users/callback');
  });
  return app.get('/users/callback', function(req, res) {
    var auth;
    auth = new Dbauth(req.url);
    return auth.getUserInfo(function(err, data) {
      if (!err) {
        return res.json(data);
      } else {
        return res.redirect('/login');
      }
    });
  });
};
