// Generated by CoffeeScript 1.6.3
var Dbauth, request, setting;

setting = require('../setting');

request = require('request');

Dbauth = (function() {
  var __getCode, __getToken;

  function Dbauth(url) {
    this.url = url;
  }

  Dbauth.prototype.getUserInfo = function(next) {
    return __getToken(this.url, function(err, token) {
      if (!err) {
        return request.get('https://api.douban.com/v2/user/~me', {
          headers: {
            'Authorization': 'Bearer ' + token
          }
        }, function(error, response, body) {
          if (!error && response.statusCode === 200) {
            return next(null, JSON.parse(body));
          } else {
            return next('error', null);
          }
        });
      }
    });
  };

  __getToken = function(url, next) {
    var code;
    code = __getCode(url);
    if (code === 'access_denied') {
      return code;
    }
    return request.post('https://www.douban.com/service/auth2/token', {
      form: {
        client_id: setting.douban_auth.client_id,
        client_secret: setting.douban_auth.client_secret,
        redirect_uri: setting.douban_auth.pro_host,
        grant_type: setting.douban_auth.grant_type,
        code: code
      }
    }, function(error, response, body) {
      if (!error && response.statusCode === 200) {
        return next(null, JSON.parse(body).access_token);
      } else {
        return next('error', null);
      }
    });
  };

  __getCode = function(url) {
    return url.split('=')[1];
  };

  return Dbauth;

})();

module.exports = Dbauth;
