// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/

var app, ejs, express, http, path, routes, user;

express = require("express");

routes = require("./routes");

user = require("./routes/user");

http = require("http");

path = require("path");

ejs = require("ejs");

app = express();

ejs.open = "{{";

ejs.close = "}}";

app.set("port", process.env.PORT || 4000);

app.set("views", path.join(__dirname, "views"));

app.set("view engine", "ejs");

app.use(express.favicon());

app.use(express.logger("dev"));

app.use(express.json());

app.use(express.urlencoded());

app.use(express.methodOverride());

app.use(express.bodyParser());

app.use(express.cookieParser());

app.use(express.session({
  secret: '1234567890QWERTY'
}));

app.use(app.router);

app.use(require("stylus").middleware(path.join(__dirname, "public")));

app.use(express["static"](path.join(__dirname, "public")));

if ("development" === app.get("env")) {
  app.use(express.errorHandler());
}

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});

routes(app);

user(app);
