# Generated by CoffeeScript 1.6.3
db = require '../lib/mysql'
pagesize = 10
People =

    get: (id,next) ->
        db.query "SELECT id,name,gravator FROM user WHERE id = ?", [id], (err,result) ->
            if err
                next err, null
            else
                next null, result
    getCollection: (uid,start,next) ->
        @__getData uid,start,0,(err,data)->
            if err
                next err,null
            else
                next null,data
    getDo: (uid,start,next) ->
        @__getData uid,start,1,(err,data)->
            if err
                next err,null
            else
                next null,data
    
    getReaded: (uid,start,next) ->
        @__getData uid,start,2,(err,data)->
            if err
                next err,null
            else
                next null,data
    
    __getData: (uid,start,status,next) ->
        sql = "SELECT COUNT(id) AS total FROM collection WHERE uid  = ? AND status = ?"
        offset =  (start - 1) * pagesize
        db.query sql,[uid,status],(err,result) ->
            
            total = result[0].total 
            pages = Math.ceil(total / pagesize)

            sql =  "SELECT b.title,(SELECT COUNT(id) FROM collection WHERE c.uid  = ? AND c.status = 0) AS total,b.isbn,b.author,b.image,b.pages,b.publisher,c.status
                    FROM books AS b,collection AS c 
                    WHERE c.isbn = b.isbn AND c.uid = ? AND c.status = ?  ORDER BY c.ctime DESC LIMIT ?,?"
            db.query sql,[uid,uid,status,offset,pagesize],(err,books) ->
                if err
                    next err, null
                else
                    data = 
                        books: books
                        total: total
                    next null, data


module.exports = People
