# Generated by CoffeeScript 1.6.3
db = require '../lib/mysql'

People = 
    get: (id,next) ->
        db.query "SELECT id,name,gravator,email FROM user WHERE id = ?", [id], (err,result) ->
            if err
                next err, null
            else
                next null, result
module.exports = People
