// Generated by CoffeeScript 1.6.3
var User, mongoose, userSchema;

mongoose = require('../lib/mongoose');

userSchema = new mongoose.Schema({
  name: {
    type: String,
    index: true,
    unique: true
  },
  email: {
    type: String,
    index: true,
    unique: true
  },
  password: String
});

module.exports = User = mongoose.model('User', userSchema);

User.save = function(info, next) {
  var user;
  user = new User;
  return user.register(info, next);
};

User.prototype.register = function(info, next) {
  var self;
  self = this;
  self.name = info.name;
  self.email = info.email;
  self.password = info.password;
  self.save();
  return next(null, info);
};

User.get = function(user, next) {
  if (user.email == null) {
    next(201);
  }
  return User.findOne({
    email: user.email
  }, function(err, dbUser) {
    if (err) {
      return next(err);
    }
    if (dbUser == null) {
      return next(err, null);
    } else {
      return next(err, dbUser);
    }
  });
};
