# Generated by CoffeeScript 1.6.3
mongoose = require '../lib/mongoose'
userSchema = new mongoose.Schema
  name:
    type: String
    index: true
    unique: true
  email:
    type: String
    index: true
    unique: true
  password: String
  motto: 
    type: String
    default: ''
module.exports = User = mongoose.model 'User', userSchema
# save user
User.save = (info,next)->
  user = new User
  user.register info,next
User::register = (info,next)->
  self = @
  self.name = info.name
  self.email = info.email
  self.password = info.password
  self.save()
  next null,info

# check user
User.get = (user,next)->
  User.findOne {email:user.email},(err,dbUser)->
    return next err if err
    if not dbUser?
      next err,null
    else
      next err,dbUser
# update post
User.modify = (args,next)->
  User.findOne({email:args.email}).exec (err,user)->
    try
      user.name = args.name
      user.motto = args.motto
      user.save()
      next null,user
    catch err
      next err,null

